# ---------------------------------------------
# docker-compose.yml - Interview Assistant
# ---------------------------------------------

version: '3.8'

services:
  backend:
    container_name: interview-backend
    build: ./backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    container_name: interview-frontend
    build: ./frontend
    ports:
      - "4200:80"
    restart: unless-stopped

# Notes:
# - Access frontend at http://localhost:4200
# - Access backend API at http://localhost:3000
# - Make sure Docker Desktop or engine is running before 'docker-compose up'
